<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="EN310366" failures="1" tests="2" name="tests.heroes.AddNewHero" time="35.934" errors="0" timestamp="2023-02-10T10:38:26 CET" skipped="1">
  <testcase classname="tests.heroes.AddNewHero" name="testAddNewHero" time="6.234">
    <skipped/>
  </testcase> <!-- testAddNewHero -->
  <system-out/>
  <testcase classname="tests.heroes.AddNewHero" name="setupTest" time="29.700">
    <failure message="Wrong Response Status Code in postUser(addnewhero230210103436) Api Call! Response Body: {&quot;timestamp&quot;:1676021684962,&quot;status&quot;:500,&quot;error&quot;:&quot;Internal Server Error&quot;,&quot;exception&quot;:&quot;org.springframework.dao.IncorrectResultSizeDataAccessException&quot;,&quot;message&quot;:&quot;result returns more than one elements; nested exception is javax.persistence.NonUniqueResultException: result returns more than one elements&quot;,&quot;path&quot;:&quot;/api/users/add&quot;} expected [200] but found [500]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Wrong Response Status Code in postUser(addnewhero230210103436) Api Call! Response Body: {"timestamp":1676021684962,"status":500,"error":"Internal Server Error","exception":"org.springframework.dao.IncorrectResultSizeDataAccessException","message":"result returns more than one elements; nested exception is javax.persistence.NonUniqueResultException: result returns more than one elements","path":"/api/users/add"} expected [200] but found [500]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:907)
at utils.RestApiUtils.postUser(RestApiUtils.java:130)
at utils.RestApiUtils.postUser(RestApiUtils.java:135)
at tests.heroes.AddNewHero.setupTest(AddNewHero.java:53)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:62)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:385)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:321)
at org.testng.internal.TestInvoker.runConfigMethods(TestInvoker.java:700)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:527)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
    </failure>
  </testcase> <!-- setupTest -->
  <system-out/>
</testsuite> <!-- tests.heroes.AddNewHero -->
